### ISSUE TITLE
JSON remote source not loaded

### ISSUE THREAD

**Issue by ghost** [drewwilson/AutoSuggest#1] opened 2010-12-30 17:04 UTC
Everything seems fine, my server-side JSON source works, no firebug errors but the list does not show up.
I'm using jQuery 1.4.4 and the non-modifies CSS file.
I also tried the wunyuntao fork on github, same problem.

**Comment by alanhogan** [comment] 2011-01-10 02:11
This is a terrible bug report. Can you contribute steps to reproduce or whatever code you’re using? No one is going to want to investigate this without something to go on.

**Comment by django-rdf-tools** [comment] 2011-01-10 10:34
I did a blank setup, with jQuery 1.4.4, css file, nothing else
In fact, it works with the static items var example
The problem is the remote json setup...still investigating, my mime-type is correct, Firebug displays and understand ('json' tab in firebug) the JSON correctly...

I checked my output , it's almost valid : see the other issue about JSONLint not validating

**Comment by django-rdf-tools** [comment] 2011-01-14 07:56
Found the problem, I was just writing 

```
items = {[ ....]}
```

in the sent json file. So it was parsed by firebug but the plugin could not find what it wanted...
Everything works now, the quote problem has gone too, I can use the same JSON source for this plugin and for the jQuery UI one, closing both issues, sorry for the false alert.

**Closed as completed by django-rdf-tools** 2011-01-14 07:56 UTC
